import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            {/* headタグとその中にアイコンやテーマカラー、manifestを記述する */}
            <head>
                <link rel='manifest' href='/ç' />
                <link rel='apple-touch-icon' href='/icon.png'></link>
                <meta name='theme-color' content='#000' />
            </head>
            <body className={inter.className}>
                <main>{children}</main>
            </body>
        </html>
    );
}
